### ISSUE TITLE
Exception type is not required for @throws tag, description is enough.

### ISSUE THREAD

**Issue by fvoronin** [docascode/type2docfx#5]
By the [JSDoc Spec](http://usejsdoc.org/tags-throws.html) `@throws` has syntax:
* `@throws free-form description`
* `@throws {<type>}`
* `@throws {<type>} free-form description`

Type2docfx (v0.9.79) works only with last of them, and the first two cause an error. 😞 
```
> type2docfx api.json .\out


...\type2docfx\dist\jsonTraverse.js:347
    if (tokens.length >= 3) {
               ^

TypeError: Cannot read property 'length' of null
    at extractException (...\type2docfx\dist\jsonTraverse.js:347:16)
    at ...\type2docfx\dist\jsonTraverse.js:231:66
    at Array.map (<anonymous>)
    at extractInformationFromSignature (...\type2docfx\dist\jsonTraverse.js:231:40)
    at traverse (...\type2docfx\dist\jsonTraverse.js:94:9)
    at ...\type2docfx\dist\jsonTraverse.js:207:17
    at Array.forEach (<anonymous>)
    at traverse (...\type2docfx\dist\jsonTraverse.js:205:23)
    at ...\type2docfx\dist\jsonTraverse.js:210:17
    at Array.forEach (<anonymous>)
```

**Comment by fvoronin** [comment]
Please, look at the example [gist](https://gist.github.com/fvoronin/8c327da7621be5375a15590df478d5cf)

**Comment by qinezh** [comment]
Closed as the issue no longer exist in latest version.
